name: Dart2_Ang5_Ex1
description: A web app that uses AngularDart Components

environment:
  sdk: '>=2.0.0-dev.51.0 <2.0.0'

dependencies:
  angular: ^5.0.0-alpha+12
  angular_components: ^0.9.0-alpha+12
  build_config: ^0.2.6
  logging: "^0.11.3+1"
  #angular_gallery_section:
    #path: ../../angular_gallery_section

dev_dependencies:
  angular_test: ^2.0.0-alpha+9
  build_runner: ^0.8.7
  build_test: ^0.10.0
  build_web_compilers: ^0.3.7
  test: ^0.12.30
  sass_builder: ^2.0.0
